<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload05f5f6356f162273d6e2d918b3f49691($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'onlyofficeplugin' => '/onlyofficePlugin.php',
            'tuleap\\onlyoffice\\plugin\\plugindescriptor' => '/Onlyoffice/Plugin/PluginDescriptor.php',
            'tuleap\\onlyoffice\\plugin\\plugininfo' => '/Onlyoffice/Plugin/PluginInfo.php',
            'tuleap\\onlyoffice\\appconfig' => '/Onlyoffice/AppConfig.php',
            'tuleap\\onlyoffice\\crypt' => '/Onlyoffice/Crypt.php',
            'tuleap\\onlyoffice\\fileutility' => '/Onlyoffice/FileUtility.php',
            'tuleap\\onlyoffice\\documentservice' => '/Onlyoffice/DocumentService.php',
            'tuleap\\onlyoffice\\controller\\getsettingscontroller' => '/Onlyoffice/Controllers/GetSettingsController.php',
            'tuleap\\onlyoffice\\controller\\savesettingscontroller' => '/Onlyoffice/Controllers/SaveSettingsController.php',
            'tuleap\\onlyoffice\\controller\\editorcontroller' => '/Onlyoffice/Controllers/EditorController.php',
            'tuleap\\onlyoffice\\controller\\downloadcontroller' => '/Onlyoffice/Controllers/DownloadController.php',
            'tuleap\\onlyoffice\\presenters\\adminpresenter' => '/Onlyoffice/Presenters/AdminPresenter.php',
            'tuleap\\onlyoffice\\presenters\\editorpresenter' => '/Onlyoffice/Presenters/EditorPresenter.php',
            'tuleap\\onlyoffice\\rest\\resourcesinjector' => '/Onlyoffice/REST/ResourcesInjector.php',
            'tuleap\\onlyoffice\\rest\\v1\\editorresource' => '/Onlyoffice/REST/v1/EditorResource.php',
            'tuleap\\onlyoffice\\rest\\v1\\callbackresource' => '/Onlyoffice/REST/v1/CallbackResource.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload05f5f6356f162273d6e2d918b3f49691');
// @codeCoverageIgnoreEnd
